version: '3'

services:
  tempconverter:
    image: ivanmarka/tempconverter:latest
    ports:
      - 80:5000
    environment:
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=db
      - DB_NAME=dbname
      - STUDENT= Ivan Markic
      - COLLEGE= Algebra University College
    depends_on:
      - db
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - tempconverter_network
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
    networks:
      - tempconverter_network

networks:
  tempconverter_network:

volumes:
  db:
